### PR TITLE
Replace archive by single file

### LINKED ISSUE #1: Adding this to https://transform.now.sh/
This looks like a really great project.

I have developed an IDE https://transform.now.sh/ and would love to have this on the site. Let me know if you can help or else, I will be happy to do it myself when I have time.

### PR DESCRIPTION
**Pull request by brikou**
closes #1 

I have to make sure tree shaking is working in my experience repo (https://github.com/brikou/CSS-in-JS-experiences) before merging to master.

### CODE REVIEW

**Comment by ritz078** [comment]
Can you make a beta release?

**Comment by brikou** [comment]
I've just published it to npm

**Comment by brikou** [comment]
@ritz078 may I ask you some help to fix tree shaking in my demo repo, here https://github.com/brikou/CSS-in-JS-experiences/tree/no_more_archive
I probably need to mark some func as pure in uglify section within webpack config, but can't make it.

**Comment by ritz078** [comment]
https://transform-bzlrdtgqzr.now.sh

Regarding this package 
- Since the functions are expressions, the order matters. It is not currently correct.
- Why did you go for functions instead of variables? Tree shaking should work for unused variables too.
- I have added a link to the Github repo on the website.

Regarding the demo repo
- have you tried using
```js
import {a, b} from 'x'
```
instead of
```js
import * as z from 'x'
```

**Comment by brikou** [comment]
@ritz078 I've released a new version, scopes are now correctly sorted, callback removed (was usefull for critical css hydration, but I'll deal with it later as non blocking).

Tree Shaking is not working as expected even with `import {a, b}` because of babel 6.x I believe, non blocking too.

Thanks for the link, people using it would be able to reach original repo :+1:

**Comment by ritz078** [comment]
https://transform-cqscjmhrul.now.sh/css-to-emotion/
There is still a bug with the order of variables.

```js
import { css, injectGlobal } from "emotion";

injectGlobal`
*, *::before, *::after {
    box-sizing: inherit;
}


@-ms-viewport {
    width: device-width;
}



















`;

export const badge = css`
  @media print {
    & {
      border: 1px solid #000;
    }
  }

  display: inline-block;
  padding: 0.25em 0.4em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: 0.25rem;

  &:empty {
    display: none;
  }
`;

export const formControl = css`
  select&:not([size]):not([multiple]) {
    height: calc(2.25rem + 2px);
  }

  &::placeholder {
    color: #868e96;
    opacity: 1;
  }
`;

export const alertDismissible = css`
  & .${close} {
    position: relative;
    top: -0.75rem;
    right: -1.25rem;
    padding: 0.75rem 1.25rem;
    color: inherit;
  }
`;

export const alertLink = css`font-weight: bold;`;

export const alertPrimary = css`
  color: #004085;
  background-color: #cce5ff;
  border-color: #b8daff;

  & hr {
    border-top-color: #9fcdff;
  }

  & .${alertLink} {
    color: #002752;
  }
`;

export const badgeDanger = css`
  color: #fff;
  background-color: #dc3545;

  &[href]:focus,
  &[href]:hover {
    color: #fff;
    text-decoration: none;
    background-color: #bd2130;
  }
`;

export const blockquoteFooter = css`
  display: block;
  font-size: 80%;
  color: #868e96;

  &::before {
    content: "\\\\2014 \\\\00A0";
  }
`;

export const close = css`
  float: right;
  font-size: 1.5rem;
  font-weight: bold;
  line-height: 1;
  color: #000;
  text-shadow: 0 1px 0 #fff;
  opacity: 0.5;
`;

export const display1 = css`
  font-size: 6rem;
  font-weight: 300;
  line-height: 1.1;
`;

export const display2 = css`
  font-size: 5.5rem;
  font-weight: 300;
  line-height: 1.1;
`;
```

You can see that `close` is used before it has been declared.

**Comment by brikou** [comment]
Ok that's why I used arrow functions, I'll bring them back and sorting too. Does it make sense to you?

**Comment by ritz078** [comment]
I don't think arrow functions are the solution here. You can surely solve this by function declarations but I think that way we are forcing our problem on the user. We need to figure out an alternative way. Maybe keep track of variable usage and sort them by that.

But I don't think this should be a blocker (for now). So I am moved this to production already with a `beta` tag.

Also, let me know your twitter handle. :)

**Comment by brikou** [comment]
Great :100: 
I used to have a getRequiredScope method (working, tested but removed with archive), I should bring it back to make sure order is correct (but it can't solve cyclic problem if any).
I think a lot of improvement can be done, like moving tag from injectGlobal to own scope with styled emotion method. And also adding of library like styled-jsx or glamor.
My twitter handle is brikou2 :bird:

**Comment by ritz078** [comment]
I would love the integration of more libraries. This is a great effort. 

Simple check that I can think of
- Prepend if already used.
- Append if not used.

**Comment by brikou** [comment]
@ritz078 I've just released v0.3.0 as sorting is now fixed, you can take a look at what it looks with bootstrap here https://github.com/brikou/CSS-in-JS-experiences/blob/master/styles/bootstrap.js
And also don't forget to update transform :+1:

**Comment by ritz078** [comment]
Updated transform :) Thank you.

**Pull request merged**
